"""Tests for runtime configuration loading."""

from topdown_shooter.config.runtime_config import RuntimeConfigLoader


def test_default_runtime_config_loads_window_and_controls() -> None:
    """Default runtime config should expose window size and controls."""
    config = RuntimeConfigLoader().load_default()

    assert config.window.width == 1280
    assert config.window.height == 720
    assert config.window.target_fps == 60
    assert config.controls.quit == "KEY_ESCAPE"
    assert config.controls.debug_overlay.key == "KEY_D"
    assert config.controls.debug_overlay.modifiers == ("KEY_LEFT_CONTROL", "KEY_RIGHT_CONTROL")
    assert config.controls.camera_up == ("KEY_UP",)
    assert config.controls.camera_down == ("KEY_DOWN",)
    assert config.controls.camera_left == ("KEY_LEFT",)
    assert config.controls.camera_right == ("KEY_RIGHT",)
    assert config.controls.camera_zoom_in == "KEY_E"
    assert config.controls.camera_zoom_out == "KEY_Q"
    assert config.controls.camera_zoom_mouse_wheel is True
    assert config.controls.camera_reset == "KEY_HOME"
    assert config.controls.camera_toggle_follow == "KEY_F"
    assert config.camera.zoom == 1.0
    assert config.camera.min_zoom == 0.5
    assert config.camera.max_zoom == 3.0
    assert config.camera.zoom_step == 0.1
    assert config.camera.move_speed_px_per_second == 720.0
    assert config.camera.clamp_to_map is True
    assert config.camera.smooth_time == 0.18
    assert config.camera.max_speed_px_per_second == 1800.0
    assert config.camera.lookahead_tiles == 3.0
    assert config.camera.dead_zone_tiles == 1.25
    assert config.camera.aim_lookahead_enabled is True
    assert config.camera.aim_lookahead_tiles == 2.0
    assert config.camera.follow_player_by_default is True
    assert config.player.marker_radius_px == 6
    assert config.player.movement_speed_px_per_second == 160.0
    assert config.player.collision_radius_px == 5
    assert config.player.max_health == 100
    assert config.aim_debug.enabled is True
    assert config.aim_debug.line_length_px == 140.0
    assert config.aim_debug.marker_radius_px == 4.0
    assert config.aim_debug.line_thickness_px == 2.0
    assert config.controls.player_up == ("KEY_W",)
    assert config.controls.player_down == ("KEY_S",)
    assert config.controls.player_left == ("KEY_A",)
    assert config.controls.player_right == ("KEY_D",)
    assert config.controls.fire_primary == "MOUSE_BUTTON_LEFT"
    assert config.controls.reload == "KEY_R"
    assert config.controls.weapon_slot_1 == "KEY_ONE"
    assert config.controls.weapon_slot_2 == "KEY_TWO"
    assert config.controls.weapon_slot_3 == "KEY_THREE"
    assert config.weapons.database_path == "res/config/weapons.json"
    assert config.debug_overlay.enabled_by_default is False
    assert config.debug_overlay.panel_width == 1200
    assert config.debug_overlay.font_path == "res/fonts/PressStart2P-Regular.ttf"
    assert config.debug_overlay.font_size == 8
    assert config.debug_overlay.font_spacing == 0.0
    assert config.debug_overlay.line_spacing == 6
    assert config.debug_overlay.section_spacing == 12
    assert config.debug_overlay.column_gap == 32
    assert config.debug_overlay.label_width == 128
    assert config.debug_overlay.background_alpha == 120
    assert config.projectile_impacts.enabled is True
    assert config.projectile_impacts.lifetime_seconds == 0.16
    assert config.projectile_impacts.radius_px == 5.0
    assert config.enemies.marker_radius_px == 6
    assert config.enemies.max_health == 100.0
    assert config.enemies.hit_marker_lifetime_seconds == 0.14
    assert config.enemies.hit_marker_radius_px == 8.0
    assert config.enemies.health_bar_visible_seconds == 1.6
    assert config.enemies.hit_flash_seconds == 0.12
    assert config.enemies.draw_view_cones is True
    assert config.enemies.vision_range_px == 320.0
    assert config.enemies.vision_angle_degrees == 80.0
    assert config.enemies.line_of_sight_sample_step_px == 8.0
    assert config.enemies.smart_initial_facing is True
    assert config.enemies.facing_candidate_step_degrees == 30.0
    assert config.enemies.facing_probe_side_angle_degrees == 25.0
    assert config.enemies.facing_wall_penalty_distance_px == 48.0
    assert config.enemies.facing_probe_step_px == 8.0
    assert config.enemies.min_squad_size == 3
    assert config.enemies.max_squad_size == 5
    assert config.enemies.squad_radius_px == 72.0
    assert config.enemies.min_enemy_spacing_px == 28.0
    assert config.enemies.max_initial_enemies == 30
    assert config.enemies.placement_attempts_per_enemy == 24
    assert config.enemies.chase_speed_px_per_second == 70.0
    assert config.enemies.preferred_combat_distance_px == 180.0
    assert config.enemies.combat_distance_tolerance_px == 40.0
    assert config.enemies.approach_weight == 0.85
    assert config.enemies.strafe_weight == 0.55
    assert config.enemies.retreat_weight == 0.75
    assert config.enemies.strafe_switch_min_seconds == 0.9
    assert config.enemies.strafe_switch_max_seconds == 1.6
    assert config.fps_counter.enabled is True
    assert config.fps_counter.position == "top_right"
    assert config.fps_counter.margin_x == 12
    assert config.fps_counter.margin_y == 12
    assert config.fps_counter.font_size == 14
    assert config.hud.enabled is True
    assert config.hud.position == "top"
    assert config.hud.margin_x == 12
    assert config.hud.margin_y == 12
    assert config.hud.padding == 8
    assert config.hud.font_size == 16
    assert config.hud.background_alpha == 150
