"""Scene overlay rendering for pilot artistic previews."""

from __future__ import annotations

import struct
import zlib
from collections import Counter
from dataclasses import dataclass
from typing import Any


Color = tuple[int, int, int]


@dataclass(frozen=True, slots=True)
class PilotSceneOverlayResult:
    """Pilot scene overlay rendering output.

    Attributes:
        preview_png: PNG image bytes with scene markers over pilot art.
        legend: Scene marker legend artifact.
        overlay_report: Compact overlay report for preparation tracking.
        overlay_summary: Human-readable overlay summary.
    """

    preview_png: bytes
    legend: dict[str, Any]
    overlay_report: dict[str, Any]
    overlay_summary: str


class PilotSceneOverlayRenderer:
    """Render scene markers over a pilot artistic preview.

    The overlay is intentionally a separate debug artifact. It must not change the
    clean pilot art preview or any gameplay data.
    """

    FAMILY_COLORS: dict[str, Color] = {
        "clearing": (210, 218, 132),
        "roadside": (218, 166, 82),
        "ruins": (188, 188, 170),
        "wetland": (106, 154, 130),
        "review": (218, 116, 116),
        "generic": (205, 160, 205),
    }
    FALLBACK_COLOR: Color = (224, 218, 142)

    def render(
        self,
        *,
        pilot_art_preview_png: bytes,
        scene_presets: dict[str, Any],
        preview_scale_px_per_tile: int | None = None,
    ) -> PilotSceneOverlayResult:
        """Render a scene-overlay pilot preview.

        Args:
            pilot_art_preview_png: Clean pilot art preview PNG generated by the
                painter preview renderer.
            scene_presets: Assigned scene preset artifact.
            preview_scale_px_per_tile: Optional known preview scale.

        Returns:
            Overlay PNG plus legend and reports.
        """
        canvas = _OverlayCanvas.from_png_bytes(pilot_art_preview_png)
        scenes = self._scene_items(scene_presets)
        rendered = 0
        family_counts: Counter[str] = Counter()
        legend_scenes: list[dict[str, Any]] = []
        scale = (
            preview_scale_px_per_tile
            if isinstance(preview_scale_px_per_tile, int) and preview_scale_px_per_tile > 0
            else self._infer_scale(canvas=canvas, scene_presets=scene_presets)
        )

        for scene in scenes:
            bounds = self._dict_value(scene, "bounds")
            center = self._dict_value(scene, "center")
            if not bounds or not center:
                continue
            preset_family = self._string_value(scene.get("preset_family"), default="generic")
            color = self.FAMILY_COLORS.get(preset_family, self.FALLBACK_COLOR)
            tile_bounds = self._tile_bounds(bounds)
            tile_center = self._tile_point(center)
            if tile_bounds is None or tile_center is None:
                continue
            self._draw_scene_marker(
                canvas=canvas,
                bounds=tile_bounds,
                center=tile_center,
                scale=scale,
                color=color,
                scene_index=rendered,
            )
            rendered += 1
            family_counts[preset_family] += 1
            legend_scenes.append(
                {
                    "id": self._string_value(scene.get("id"), default=f"scene_{rendered - 1:03d}"),
                    "scene_type": self._string_value(scene.get("scene_type"), default="unknown"),
                    "preset_id": self._string_value(scene.get("preset_id"), default="unknown"),
                    "preset_family": preset_family,
                    "color_rgb": list(color),
                    "bounds": bounds,
                    "center": center,
                },
            )

        report = self._build_report(
            canvas=canvas,
            scale=scale,
            total_scenes=len(scenes),
            rendered_scenes=rendered,
            family_counts=family_counts,
        )
        return PilotSceneOverlayResult(
            preview_png=canvas.to_png_bytes(),
            legend=self._build_legend(scale=scale, scenes=legend_scenes, family_counts=family_counts),
            overlay_report=report,
            overlay_summary=self.format_summary(report),
        )

    def format_summary(self, report: dict[str, Any]) -> str:
        """Format scene overlay summary as readable text.

        Args:
            report: Overlay report dictionary.

        Returns:
            Human-readable summary.
        """
        rendered = self._dict_value(report, "rendered")
        dimensions = self._dict_value(report, "dimensions")
        return "\n".join(
            [
                "Pilot scene overlay preview",
                f"- status: {report.get('status', 'unknown')}",
                (
                    "- image: "
                    f"{dimensions.get('preview_width_px', 'unknown')}x"
                    f"{dimensions.get('preview_height_px', 'unknown')} px"
                ),
                f"- preview scale: {dimensions.get('preview_scale_px_per_tile', 'unknown')}",
                f"- scene markers: {rendered.get('scene_markers', 'unknown')}",
                f"- total scenes: {rendered.get('total_scenes', 'unknown')}",
            ],
        )

    def _draw_scene_marker(
        self,
        *,
        canvas: "_OverlayCanvas",
        bounds: tuple[int, int, int, int],
        center: tuple[int, int],
        scale: int,
        color: Color,
        scene_index: int,
    ) -> None:
        """Draw one scene marker.

        Args:
            canvas: Overlay canvas.
            bounds: Tile-space bounds as ``x, y, width, height``.
            center: Tile-space scene center.
            scale: Preview pixels per tile.
            color: Marker RGB color.
            scene_index: Zero-based rendered scene index.
        """
        x, y, width, height = bounds
        left = x * scale
        top = y * scale
        right = (x + width) * scale - 1
        bottom = (y + height) * scale - 1
        canvas.blend_rect(left, top, max(1, right - left + 1), 1, color, alpha=0.40)
        canvas.blend_rect(left, bottom, max(1, right - left + 1), 1, color, alpha=0.40)
        canvas.blend_rect(left, top, 1, max(1, bottom - top + 1), color, alpha=0.40)
        canvas.blend_rect(right, top, 1, max(1, bottom - top + 1), color, alpha=0.40)

        center_x, center_y = center
        px = center_x * scale + scale // 2
        py = center_y * scale + scale // 2
        radius = max(2, scale // 4)
        canvas.blend_rect(px - radius, py, radius * 2 + 1, 1, color, alpha=0.85)
        canvas.blend_rect(px, py - radius, 1, radius * 2 + 1, color, alpha=0.85)
        canvas.blend_ellipse(px, py, max(2, scale // 5), max(2, scale // 5), color, alpha=0.55)
        self._draw_index_tag(canvas=canvas, x=left + 2, y=top + 2, index=scene_index, color=color)

    def _draw_index_tag(
        self,
        *,
        canvas: "_OverlayCanvas",
        x: int,
        y: int,
        index: int,
        color: Color,
    ) -> None:
        """Draw a tiny deterministic scene index tag.

        Args:
            canvas: Overlay canvas.
            x: Left pixel coordinate.
            y: Top pixel coordinate.
            index: Scene index to encode.
            color: Tag color.
        """
        tag_width = 10
        tag_height = 6
        canvas.blend_rect(x, y, tag_width, tag_height, (12, 14, 12), alpha=0.55)
        first = (index // 10) % 10
        second = index % 10
        self._draw_digit(canvas=canvas, x=x + 1, y=y + 1, digit=first, color=color)
        self._draw_digit(canvas=canvas, x=x + 5, y=y + 1, digit=second, color=color)

    def _draw_digit(
        self,
        *,
        canvas: "_OverlayCanvas",
        x: int,
        y: int,
        digit: int,
        color: Color,
    ) -> None:
        """Draw one tiny 3x5 digit.

        Args:
            canvas: Overlay canvas.
            x: Left pixel coordinate.
            y: Top pixel coordinate.
            digit: Digit in range 0..9.
            color: Digit color.
        """
        glyphs = {
            0: ("111", "101", "101", "101", "111"),
            1: ("010", "110", "010", "010", "111"),
            2: ("111", "001", "111", "100", "111"),
            3: ("111", "001", "111", "001", "111"),
            4: ("101", "101", "111", "001", "001"),
            5: ("111", "100", "111", "001", "111"),
            6: ("111", "100", "111", "101", "111"),
            7: ("111", "001", "010", "010", "010"),
            8: ("111", "101", "111", "101", "111"),
            9: ("111", "101", "111", "001", "111"),
        }
        glyph = glyphs.get(digit, glyphs[0])
        for row_index, row in enumerate(glyph):
            for col_index, value in enumerate(row):
                if value == "1":
                    canvas.blend_rect(x + col_index, y + row_index, 1, 1, color, alpha=0.95)

    def _tile_bounds(self, bounds: dict[str, Any]) -> tuple[int, int, int, int] | None:
        """Return normalized tile bounds.

        Args:
            bounds: Raw bounds dictionary.

        Returns:
            Bounds tuple or ``None`` when malformed.
        """
        min_x = self._optional_int(bounds.get("min_x", bounds.get("x")))
        min_y = self._optional_int(bounds.get("min_y", bounds.get("y")))
        max_x = self._optional_int(bounds.get("max_x"))
        max_y = self._optional_int(bounds.get("max_y"))
        width = self._optional_int(bounds.get("width", bounds.get("w")))
        height = self._optional_int(bounds.get("height", bounds.get("h")))
        if min_x is None or min_y is None:
            return None
        if width is None and max_x is not None:
            width = max_x - min_x + 1
        if height is None and max_y is not None:
            height = max_y - min_y + 1
        if width is None or height is None:
            width = 1
            height = 1
        return (min_x, min_y, max(1, width), max(1, height))

    def _tile_point(self, point: dict[str, Any]) -> tuple[int, int] | None:
        """Return a normalized tile point.

        Args:
            point: Raw point dictionary.

        Returns:
            Point tuple or ``None`` when malformed.
        """
        x = self._optional_int(point.get("x"))
        y = self._optional_int(point.get("y"))
        if x is None or y is None:
            return None
        return (x, y)

    def _scene_items(self, scene_presets: dict[str, Any]) -> list[dict[str, Any]]:
        """Return scene preset entries.

        Args:
            scene_presets: Scene presets artifact.

        Returns:
            Scene preset dictionaries.
        """
        scenes = scene_presets.get("scenes")
        if not isinstance(scenes, list):
            return []
        return [scene for scene in scenes if isinstance(scene, dict)]

    def _infer_scale(self, *, canvas: "_OverlayCanvas", scene_presets: dict[str, Any]) -> int:
        """Infer preview scale from scene coordinates and image size.

        Args:
            canvas: Decoded pilot preview canvas.
            scene_presets: Scene preset artifact.

        Returns:
            Inferred pixels per tile.
        """
        max_tile_x = 0
        max_tile_y = 0
        for scene in self._scene_items(scene_presets):
            bounds = self._tile_bounds(self._dict_value(scene, "bounds"))
            if bounds is None:
                continue
            x, y, width, height = bounds
            max_tile_x = max(max_tile_x, x + width)
            max_tile_y = max(max_tile_y, y + height)
        candidates = []
        if max_tile_x > 0:
            candidates.append(canvas.width // max_tile_x)
        if max_tile_y > 0:
            candidates.append(canvas.height // max_tile_y)
        valid = [candidate for candidate in candidates if candidate > 0]
        return max(1, min(valid) if valid else 16)

    def _build_legend(
        self,
        *,
        scale: int,
        scenes: list[dict[str, Any]],
        family_counts: Counter[str],
    ) -> dict[str, Any]:
        """Build scene overlay legend.

        Args:
            scale: Preview pixels per tile.
            scenes: Rendered scene legend entries.
            family_counts: Rendered scene counts by family.

        Returns:
            JSON-serializable legend.
        """
        return {
            "schema_version": "pilot-scene-overlay-legend-v1",
            "purpose": "Scene annotation overlay for pilot artistic preview.",
            "overlay_policy": {
                "clean_preview_is_unchanged": True,
                "gameplay_changes": False,
                "bounds": "Thin translucent rectangles in preset-family color.",
                "center": "Small cross and dot at scene center.",
                "label": "Tiny two-digit scene index tag; full metadata is stored in this legend.",
            },
            "preview_scale_px_per_tile": scale,
            "preset_family_colors_rgb": {
                family: list(color)
                for family, color in sorted(self.FAMILY_COLORS.items())
            },
            "rendered_counts_by_preset_family": dict(sorted(family_counts.items())),
            "scenes": scenes,
        }

    def _build_report(
        self,
        *,
        canvas: "_OverlayCanvas",
        scale: int,
        total_scenes: int,
        rendered_scenes: int,
        family_counts: Counter[str],
    ) -> dict[str, Any]:
        """Build overlay report.

        Args:
            canvas: Overlay canvas.
            scale: Preview pixels per tile.
            total_scenes: Total input scenes.
            rendered_scenes: Rendered scene count.
            family_counts: Rendered scene counts by family.

        Returns:
            JSON-serializable report.
        """
        status = "ok" if rendered_scenes == total_scenes or total_scenes == 0 else "warning"
        return {
            "schema_version": "pilot-scene-overlay-report-v1",
            "status": status,
            "dimensions": {
                "preview_width_px": canvas.width,
                "preview_height_px": canvas.height,
                "preview_scale_px_per_tile": scale,
            },
            "rendered": {
                "total_scenes": total_scenes,
                "scene_markers": rendered_scenes,
                "counts_by_preset_family": dict(sorted(family_counts.items())),
            },
            "contract": {
                "changes_gameplay": False,
                "changes_collision": False,
                "moves_markers": False,
            },
        }

    def _dict_value(self, data: dict[str, Any], key: str) -> dict[str, Any]:
        """Return a nested dictionary value.

        Args:
            data: Source dictionary.
            key: Key to read.

        Returns:
            Nested dictionary or empty dictionary.
        """
        value = data.get(key)
        return value if isinstance(value, dict) else {}

    def _optional_int(self, value: Any) -> int | None:
        """Return an integer or ``None`` from raw data.

        Args:
            value: Raw value.

        Returns:
            Integer value or ``None``.
        """
        return value if isinstance(value, int) and not isinstance(value, bool) else None

    def _string_value(self, value: Any, *, default: str) -> str:
        """Return a stripped string.

        Args:
            value: Raw value.
            default: Fallback value.

        Returns:
            String value or fallback.
        """
        if isinstance(value, str) and value.strip():
            return value.strip()
        return default


class _OverlayCanvas:
    """RGB canvas decoded from the generated pilot preview PNG."""

    def __init__(self, *, width: int, height: int, pixels: bytearray) -> None:
        """Initialize the canvas.

        Args:
            width: Image width in pixels.
            height: Image height in pixels.
            pixels: RGB pixel buffer.
        """
        self.width = max(1, width)
        self.height = max(1, height)
        self._pixels = pixels

    @classmethod
    def from_png_bytes(cls, png_bytes: bytes) -> "_OverlayCanvas":
        """Decode a generated RGB PNG.

        Args:
            png_bytes: PNG image bytes.

        Returns:
            Decoded overlay canvas.

        Raises:
            ValueError: If the PNG is unsupported or malformed.
        """
        if not png_bytes.startswith(b"\x89PNG\r\n\x1a\n"):
            raise ValueError("Pilot art preview is not a PNG image.")
        offset = 8
        width = 0
        height = 0
        idat_parts: list[bytes] = []
        while offset + 8 <= len(png_bytes):
            length = struct.unpack(">I", png_bytes[offset:offset + 4])[0]
            chunk_type = png_bytes[offset + 4:offset + 8]
            chunk_data = png_bytes[offset + 8:offset + 8 + length]
            offset += 12 + length
            if chunk_type == b"IHDR":
                width, height, bit_depth, color_type, compression, filter_method, interlace = struct.unpack(
                    ">IIBBBBB",
                    chunk_data,
                )
                if bit_depth != 8 or color_type != 2 or compression != 0 or filter_method != 0 or interlace != 0:
                    raise ValueError("Unsupported pilot art preview PNG format.")
            elif chunk_type == b"IDAT":
                idat_parts.append(chunk_data)
            elif chunk_type == b"IEND":
                break
        if width <= 0 or height <= 0:
            raise ValueError("Pilot art preview PNG is missing dimensions.")
        raw = zlib.decompress(b"".join(idat_parts))
        row_stride = width * 3
        expected = height * (row_stride + 1)
        if len(raw) != expected:
            raise ValueError("Pilot art preview PNG has unexpected image data length.")
        pixels = bytearray(width * height * 3)
        for row_index in range(height):
            source = row_index * (row_stride + 1)
            if raw[source] != 0:
                raise ValueError("Unsupported PNG row filter in pilot art preview.")
            target = row_index * row_stride
            pixels[target:target + row_stride] = raw[source + 1:source + 1 + row_stride]
        return cls(width=width, height=height, pixels=pixels)

    def blend_rect(self, x: int, y: int, width: int, height: int, color: Color, *, alpha: float) -> None:
        """Alpha-blend a rectangle.

        Args:
            x: Left pixel coordinate.
            y: Top pixel coordinate.
            width: Rectangle width.
            height: Rectangle height.
            color: RGB color.
            alpha: Blend factor in ``[0, 1]``.
        """
        left = max(0, x)
        top = max(0, y)
        right = min(self.width, x + max(0, width))
        bottom = min(self.height, y + max(0, height))
        if right <= left or bottom <= top:
            return
        alpha = max(0.0, min(1.0, alpha))
        inv_alpha = 1.0 - alpha
        for py in range(top, bottom):
            for px in range(left, right):
                self._blend_pixel(px, py, color, alpha=alpha, inv_alpha=inv_alpha)

    def blend_ellipse(
        self,
        center_x: int,
        center_y: int,
        radius_x: int,
        radius_y: int,
        color: Color,
        *,
        alpha: float,
    ) -> None:
        """Alpha-blend a filled ellipse.

        Args:
            center_x: Center X pixel coordinate.
            center_y: Center Y pixel coordinate.
            radius_x: Horizontal radius.
            radius_y: Vertical radius.
            color: RGB color.
            alpha: Blend factor in ``[0, 1]``.
        """
        radius_x = max(1, radius_x)
        radius_y = max(1, radius_y)
        alpha = max(0.0, min(1.0, alpha))
        inv_alpha = 1.0 - alpha
        left = max(0, center_x - radius_x)
        right = min(self.width - 1, center_x + radius_x)
        top = max(0, center_y - radius_y)
        bottom = min(self.height - 1, center_y + radius_y)
        rx2 = radius_x * radius_x
        ry2 = radius_y * radius_y
        threshold = rx2 * ry2
        for py in range(top, bottom + 1):
            dy = py - center_y
            for px in range(left, right + 1):
                dx = px - center_x
                if dx * dx * ry2 + dy * dy * rx2 <= threshold:
                    self._blend_pixel(px, py, color, alpha=alpha, inv_alpha=inv_alpha)

    def to_png_bytes(self) -> bytes:
        """Encode canvas as PNG bytes.

        Returns:
            PNG bytes.
        """
        rows = bytearray()
        row_stride = self.width * 3
        for row_index in range(self.height):
            rows.append(0)
            start = row_index * row_stride
            rows.extend(self._pixels[start:start + row_stride])
        return b"".join(
            [
                b"\x89PNG\r\n\x1a\n",
                self._png_chunk(
                    b"IHDR",
                    struct.pack(">IIBBBBB", self.width, self.height, 8, 2, 0, 0, 0),
                ),
                self._png_chunk(b"IDAT", zlib.compress(bytes(rows), level=6)),
                self._png_chunk(b"IEND", b""),
            ],
        )

    def _blend_pixel(self, x: int, y: int, color: Color, *, alpha: float, inv_alpha: float) -> None:
        """Blend one pixel.

        Args:
            x: Pixel X coordinate.
            y: Pixel Y coordinate.
            color: RGB color.
            alpha: Blend factor.
            inv_alpha: Inverted blend factor.
        """
        offset = (y * self.width + x) * 3
        red, green, blue = color
        self._pixels[offset] = int(self._pixels[offset] * inv_alpha + red * alpha)
        self._pixels[offset + 1] = int(self._pixels[offset + 1] * inv_alpha + green * alpha)
        self._pixels[offset + 2] = int(self._pixels[offset + 2] * inv_alpha + blue * alpha)

    def _png_chunk(self, chunk_type: bytes, data: bytes) -> bytes:
        """Build one PNG chunk.

        Args:
            chunk_type: Four-byte PNG chunk type.
            data: Chunk payload.

        Returns:
            PNG chunk bytes.
        """
        checksum = zlib.crc32(chunk_type)
        checksum = zlib.crc32(data, checksum) & 0xFFFFFFFF
        return struct.pack(">I", len(data)) + chunk_type + data + struct.pack(">I", checksum)
