"""Scene ranking and visual quality gates for prepared maps."""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True, slots=True)
class VisualQualityResult:
    """Visual quality gate output.

    Attributes:
        scene_ranking: Ranked accepted/rejected visual scenes.
        quality_report: Compact visual quality report.
        quality_summary: Human-readable visual quality summary.
    """

    scene_ranking: dict[str, Any]
    quality_report: dict[str, Any]
    quality_summary: str


class VisualQualityAnalyzer:
    """Rank scene candidates and build non-blocking visual quality gates."""

    MIN_CLEARING_AREA = 24
    MIN_WATER_AREA = 2
    MAX_ACCEPTED_SCENES = 64
    GENERIC_OK_RATIO = 0.05
    GENERIC_WARNING_RATIO = 0.15
    GENERIC_OK_MAX_COUNT = 8
    GENERIC_WARNING_MAX_COUNT = 50

    TYPE_WEIGHTS = {
        "ruin_scene": 120,
        "road_junction_scene": 90,
        "water_scene": 70,
        "clearing_scene": 30,
    }

    SCENE_TYPES = {
        "clearing_scene": "main_clearing",
        "road_junction_scene": "road_junction",
        "ruin_scene": "ruin_cluster",
        "water_scene": "water_lowland",
    }

    def analyze(
        self,
        *,
        visual_summary: dict[str, Any],
        scene_candidates: dict[str, Any],
    ) -> VisualQualityResult:
        """Analyze visual scene candidates and visual-map quality.

        Args:
            visual_summary: Visual map summary generated by preparation.
            scene_candidates: Scene candidate artifact from ``VisualContextAnalyzer``.

        Returns:
            Visual quality result with ranking, JSON report, and text summary.
        """
        ranking = self._rank_scene_candidates(scene_candidates)
        report = self._build_quality_report(
            visual_summary=visual_summary,
            scene_candidates=scene_candidates,
            scene_ranking=ranking,
        )
        summary = self.format_quality_summary(report)
        return VisualQualityResult(
            scene_ranking=ranking,
            quality_report=report,
            quality_summary=summary,
        )

    def format_quality_summary(self, report: dict[str, Any]) -> str:
        """Format visual quality gates as readable text.

        Args:
            report: Visual quality report dictionary.

        Returns:
            Human-readable summary.
        """
        readiness = self._dict_value(report, "visual_map_readiness")
        generic = self._dict_value(report, "generic_objects")
        scenes = self._dict_value(report, "scene_ranking")
        rejection_counts = self._dict_value(scenes, "rejected_counts_by_reason")
        return "\n".join(
            [
                "Visual quality gates",
                f"- status: {report.get('status', 'unknown')}",
                f"- visual map: {readiness.get('status', 'unknown')}",
                f"- visual objects: {generic.get('total_objects', 'unknown')}",
                (
                    "- generic objects: "
                    f"{generic.get('generic_objects', 'unknown')} "
                    f"({generic.get('generic_ratio_percent', 'unknown')}%) "
                    f"{generic.get('status', 'unknown')}"
                ),
                f"- scene candidates: {scenes.get('total_candidates', 'unknown')}",
                f"- accepted scenes: {scenes.get('accepted_scenes', 'unknown')}",
                f"- rejected scenes: {scenes.get('rejected_candidates', 'unknown')}",
                (
                    "- rejected as too small: "
                    f"{rejection_counts.get('too_small', 0)}"
                ),
                (
                    "- rejected as corridor/noise: "
                    f"{rejection_counts.get('corridor_like', 0)}"
                ),
            ],
        )

    def _rank_scene_candidates(self, scene_candidates: dict[str, Any]) -> dict[str, Any]:
        """Rank scene candidates into accepted scenes and rejected noise.

        Args:
            scene_candidates: Raw scene candidate artifact.

        Returns:
            Scene ranking artifact.
        """
        candidates = self._candidate_items(scene_candidates)
        accepted: list[dict[str, Any]] = []
        rejected: list[dict[str, Any]] = []

        for candidate in candidates:
            decision = self._classify_candidate(candidate)
            if decision["accepted"]:
                accepted.append(self._accepted_scene(candidate, len(accepted), decision))
            else:
                rejected.append(self._rejected_candidate(candidate, decision))

        accepted.sort(key=self._accepted_sort_key)
        accepted = [self._renumber_scene(scene, index) for index, scene in enumerate(accepted)]

        if len(accepted) > self.MAX_ACCEPTED_SCENES:
            overflow = accepted[self.MAX_ACCEPTED_SCENES :]
            accepted = accepted[: self.MAX_ACCEPTED_SCENES]
            rejected.extend(
                self._overflow_rejection(scene)
                for scene in overflow
            )

        accepted_type_counts = Counter(str(scene["scene_type"]) for scene in accepted)
        rejected_reason_counts = Counter(str(item["reason"]) for item in rejected)
        return {
            "schema_version": "visual-scene-ranking-v1",
            "thresholds": {
                "min_clearing_area": self.MIN_CLEARING_AREA,
                "min_water_area": self.MIN_WATER_AREA,
                "max_accepted_scenes": self.MAX_ACCEPTED_SCENES,
            },
            "accepted_scenes": accepted,
            "rejected_candidates": rejected,
            "summary": {
                "total_candidates": len(candidates),
                "accepted_scenes": len(accepted),
                "rejected_candidates": len(rejected),
                "accepted_counts_by_scene_type": dict(sorted(accepted_type_counts.items())),
                "rejected_counts_by_reason": dict(sorted(rejected_reason_counts.items())),
            },
        }

    def _classify_candidate(self, candidate: dict[str, Any]) -> dict[str, Any]:
        """Classify a candidate as accepted or rejected.

        Args:
            candidate: Candidate dictionary.

        Returns:
            Decision dictionary.
        """
        candidate_type = str(candidate.get("candidate_type", "unknown"))
        priority = self._int_value(candidate.get("priority"), default=0)
        bounds = self._dict_value(candidate, "bounds")
        width = self._bounds_span(bounds, "x")
        height = self._bounds_span(bounds, "y")

        if candidate_type == "clearing_scene":
            if priority < self.MIN_CLEARING_AREA:
                return {"accepted": False, "reason": "too_small"}
            if min(width, height) <= 1:
                return {"accepted": False, "reason": "corridor_like"}
            return self._accepted_decision(candidate_type, priority)

        if candidate_type == "water_scene":
            if priority < self.MIN_WATER_AREA:
                return {"accepted": False, "reason": "too_small"}
            return self._accepted_decision(candidate_type, priority)

        if candidate_type in {"ruin_scene", "road_junction_scene"}:
            return self._accepted_decision(candidate_type, priority)

        return {"accepted": False, "reason": "unsupported_type"}

    def _accepted_decision(self, candidate_type: str, priority: int) -> dict[str, Any]:
        """Build an accepted decision.

        Args:
            candidate_type: Candidate type label.
            priority: Candidate priority.

        Returns:
            Accepted decision dictionary.
        """
        return {
            "accepted": True,
            "scene_type": self.SCENE_TYPES.get(candidate_type, "generic_scene"),
            "score": self.TYPE_WEIGHTS.get(candidate_type, 0) + priority,
        }

    def _accepted_scene(
        self,
        candidate: dict[str, Any],
        index: int,
        decision: dict[str, Any],
    ) -> dict[str, Any]:
        """Convert a candidate into an accepted scene entry.

        Args:
            candidate: Source candidate.
            index: Temporary sequence index.
            decision: Accepted decision.

        Returns:
            Accepted scene dictionary.
        """
        candidate_type = str(candidate.get("candidate_type", "unknown"))
        return {
            "id": f"scene_{index:03d}",
            "source_candidate_id": str(candidate.get("id", "unknown")),
            "candidate_type": candidate_type,
            "scene_type": str(decision.get("scene_type", "generic_scene")),
            "score": self._int_value(decision.get("score"), default=0),
            "priority": self._int_value(candidate.get("priority"), default=0),
            "bounds": self._dict_value(candidate, "bounds"),
            "center": self._dict_value(candidate, "center"),
            "source": str(candidate.get("source", "unknown")),
        }

    def _rejected_candidate(
        self,
        candidate: dict[str, Any],
        decision: dict[str, Any],
    ) -> dict[str, Any]:
        """Convert a candidate into a rejected candidate entry.

        Args:
            candidate: Source candidate.
            decision: Rejection decision.

        Returns:
            Rejected candidate dictionary.
        """
        return {
            "source_candidate_id": str(candidate.get("id", "unknown")),
            "candidate_type": str(candidate.get("candidate_type", "unknown")),
            "reason": str(decision.get("reason", "unknown")),
            "priority": self._int_value(candidate.get("priority"), default=0),
            "bounds": self._dict_value(candidate, "bounds"),
            "center": self._dict_value(candidate, "center"),
        }

    def _overflow_rejection(self, scene: dict[str, Any]) -> dict[str, Any]:
        """Build a rejection entry for scene-budget overflow.

        Args:
            scene: Accepted scene trimmed by the max-scene budget.

        Returns:
            Rejected candidate dictionary.
        """
        return {
            "source_candidate_id": str(scene.get("source_candidate_id", "unknown")),
            "candidate_type": str(scene.get("candidate_type", "unknown")),
            "reason": "scene_budget_overflow",
            "priority": self._int_value(scene.get("priority"), default=0),
            "bounds": self._dict_value(scene, "bounds"),
            "center": self._dict_value(scene, "center"),
        }

    def _renumber_scene(self, scene: dict[str, Any], index: int) -> dict[str, Any]:
        """Return scene with stable sorted sequence id.

        Args:
            scene: Scene dictionary.
            index: Sorted scene index.

        Returns:
            Renumbered scene dictionary.
        """
        updated = dict(scene)
        updated["id"] = f"scene_{index:03d}"
        return updated

    def _build_quality_report(
        self,
        *,
        visual_summary: dict[str, Any],
        scene_candidates: dict[str, Any],
        scene_ranking: dict[str, Any],
    ) -> dict[str, Any]:
        """Build visual quality report.

        Args:
            visual_summary: Visual map summary.
            scene_candidates: Raw scene candidate artifact.
            scene_ranking: Ranked scenes artifact.

        Returns:
            Visual quality report dictionary.
        """
        readiness = self._build_readiness(visual_summary)
        generic = self._build_generic_quality(visual_summary)
        scene_quality = self._build_scene_quality(scene_candidates, scene_ranking)
        checks = [
            self._check(
                "visual_map_readiness",
                str(readiness["status"]),
                "Visual map artifact set should be present for baked runtime rendering.",
            ),
            self._check(
                "generic_object_ratio",
                str(generic["status"]),
                "Generic visual objects should be reduced before final art rendering.",
            ),
            self._check(
                "scene_ranking",
                str(scene_quality["status"]),
                "Scene candidates should produce a bounded accepted scene list.",
            ),
        ]
        return {
            "schema_version": "visual-quality-report-v1",
            "status": self._quality_status(checks),
            "visual_map_readiness": readiness,
            "generic_objects": generic,
            "scene_ranking": scene_quality,
            "checks": checks,
        }

    def _build_readiness(self, visual_summary: dict[str, Any]) -> dict[str, Any]:
        """Build visual map readiness section.

        Args:
            visual_summary: Visual map summary.

        Returns:
            Readiness dictionary.
        """
        present = visual_summary.get("present") is True
        required = {
            "visual_map": present,
            "visual_layers": self._int_value(visual_summary.get("layers_count"), default=0) > 0,
            "visual_objects": self._int_value(visual_summary.get("objects_count"), default=0) > 0,
            "visual_chunks": self._int_value(visual_summary.get("chunks_count"), default=0) > 0,
            "preview_png": visual_summary.get("preview_png") is True,
            "final_render_png": visual_summary.get("final_render_png") is True,
        }
        missing = [name for name, is_present in required.items() if not is_present]
        if not present:
            status = "missing"
        elif missing:
            status = "warning"
        else:
            status = "ok"
        return {
            "status": status,
            "present": present,
            "missing_artifacts": missing,
            "artifacts": required,
        }

    def _build_generic_quality(self, visual_summary: dict[str, Any]) -> dict[str, Any]:
        """Build generic-object quality section.

        Args:
            visual_summary: Visual map summary.

        Returns:
            Generic object quality dictionary.
        """
        total_objects = self._int_value(visual_summary.get("objects_count"), default=0)
        generic_objects = self._int_value(visual_summary.get("generic_objects_count"), default=0)
        ratio = generic_objects / total_objects if total_objects > 0 else 0.0
        if (
            generic_objects <= self.GENERIC_OK_MAX_COUNT
            and ratio <= self.GENERIC_OK_RATIO
        ):
            status = "ok"
        elif (
            generic_objects <= self.GENERIC_WARNING_MAX_COUNT
            and ratio <= self.GENERIC_WARNING_RATIO
        ):
            status = "warning"
        else:
            status = "bad"
        return {
            "status": status,
            "total_objects": total_objects,
            "generic_objects": generic_objects,
            "generic_ratio": round(ratio, 4),
            "generic_ratio_percent": round(ratio * 100.0, 2),
            "thresholds": {
                "ok_max_ratio": self.GENERIC_OK_RATIO,
                "warning_max_ratio": self.GENERIC_WARNING_RATIO,
                "ok_max_count": self.GENERIC_OK_MAX_COUNT,
                "warning_max_count": self.GENERIC_WARNING_MAX_COUNT,
            },
        }

    def _build_scene_quality(
        self,
        scene_candidates: dict[str, Any],
        scene_ranking: dict[str, Any],
    ) -> dict[str, Any]:
        """Build scene ranking quality section.

        Args:
            scene_candidates: Raw scene candidate artifact.
            scene_ranking: Ranked scenes artifact.

        Returns:
            Scene quality dictionary.
        """
        candidate_summary = self._dict_value(scene_candidates, "summary")
        ranking_summary = self._dict_value(scene_ranking, "summary")
        accepted = self._int_value(ranking_summary.get("accepted_scenes"), default=0)
        total = self._int_value(candidate_summary.get("total_candidates"), default=0)
        if accepted > 0:
            status = "ok"
        elif total > 0:
            status = "warning"
        else:
            status = "missing"
        return {
            "status": status,
            "total_candidates": total,
            "accepted_scenes": accepted,
            "rejected_candidates": self._int_value(
                ranking_summary.get("rejected_candidates"),
                default=0,
            ),
            "accepted_counts_by_scene_type": self._dict_value(
                ranking_summary,
                "accepted_counts_by_scene_type",
            ),
            "rejected_counts_by_reason": self._dict_value(
                ranking_summary,
                "rejected_counts_by_reason",
            ),
        }

    def _quality_status(self, checks: list[dict[str, str]]) -> str:
        """Return non-blocking quality status.

        Args:
            checks: Quality checks.

        Returns:
            Quality status for reports.
        """
        statuses = {check["status"] for check in checks}
        if "bad" in statuses or "missing" in statuses:
            return "needs_work"
        if "warning" in statuses:
            return "warning"
        return "ok"

    def _check(self, code: str, status: str, message: str) -> dict[str, str]:
        """Build a quality check entry.

        Args:
            code: Stable check code.
            status: Check status.
            message: Human-readable check message.

        Returns:
            Check dictionary.
        """
        return {"code": code, "status": status, "message": message}

    def _candidate_items(self, scene_candidates: dict[str, Any]) -> list[dict[str, Any]]:
        """Extract candidate dictionaries from artifact.

        Args:
            scene_candidates: Scene candidate artifact.

        Returns:
            Candidate dictionaries.
        """
        items = scene_candidates.get("candidates", [])
        if not isinstance(items, list):
            return []
        return [item for item in items if isinstance(item, dict)]

    def _accepted_sort_key(self, scene: dict[str, Any]) -> tuple[int, int, str]:
        """Build deterministic sort key for accepted scenes.

        Args:
            scene: Accepted scene dictionary.

        Returns:
            Sort key tuple.
        """
        return (
            -self._int_value(scene.get("score"), default=0),
            -self._int_value(scene.get("priority"), default=0),
            str(scene.get("source_candidate_id", "")),
        )

    def _bounds_span(self, bounds: dict[str, Any], axis: str) -> int:
        """Return inclusive bounds span for an axis.

        Args:
            bounds: Bounds dictionary with ``min_*`` / ``max_*`` keys.
            axis: Axis name, either ``x`` or ``y``.

        Returns:
            Inclusive span, or zero when malformed.
        """
        min_value = self._int_value(bounds.get(f"min_{axis}"), default=0)
        max_value = self._int_value(bounds.get(f"max_{axis}"), default=-1)
        return max(0, max_value - min_value + 1)

    def _dict_value(self, data: dict[str, Any], key: str) -> dict[str, Any]:
        """Return nested dictionary value.

        Args:
            data: Source dictionary.
            key: Key to read.

        Returns:
            Nested dictionary or empty dictionary.
        """
        value = data.get(key)
        return value if isinstance(value, dict) else {}

    def _int_value(self, value: Any, *, default: int) -> int:
        """Return an integer from raw JSON-like data.

        Args:
            value: Raw value.
            default: Fallback value.

        Returns:
            Integer value or fallback.
        """
        return value if isinstance(value, int) and not isinstance(value, bool) else default
